### ISSUE TITLE
ADRNet

### ISSUE THREAD

**Issue by aibc-hp** [easycodesniper-afk/SiamCSR#2]
您好，我想问一个关于ADRNet的问题，我在那里看到了您问作者的问题，RuntimeError: Error building extension  _prroi_pooling，您说您已经解决了该问题，我想问一下您是怎么解决的呢？能否详细说说？
我也遇到了一样的问题，目前在这问题上已经用了两天时间，尝试了很多方法，但还是无法解决。
非常迫切的希望能收到您的回复！

**Comment by easycodesniper-afk** [comment]
我记得是贴了一个博客链接在里面，用那个博客里的方法解决的





------------------ Original ------------------
From: aibc-hp ***@***.***&gt;
Date: Wed,Apr 6,2022 11:05 PM
To: easycodesniper-afk/SiamCSR ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [easycodesniper-afk/SiamCSR] ADRNet (Issue #2)





 
您好，我想问一个关于ADRNet的问题，我在那里看到了您问作者的问题，RuntimeError: Error building extension  _prroi_pooling，您说您已经解决了该问题，我想问一下您是怎么解决的呢？能否详细说说？
 我也遇到了一样的问题，目前在这问题上已经用了两天时间，尝试了很多方法，但还是无法解决。
 非常迫切的希望能收到您的回复！

**Comment by easycodesniper-afk** [comment]
> 您好，我想问一个关于ADRNet的问题，我在那里看到了您问作者的问题，RuntimeError: Error building extension _prroi_pooling，您说您已经解决了该问题，我想问一下您是怎么解决的呢？能否详细说说？ 我也遇到了一样的问题，目前在这问题上已经用了两天时间，尝试了很多方法，但还是无法解决。 非常迫切的希望能收到您的回复！

https://blog.csdn.net/dongwanli666/article/details/104656679

参考这个博客

**Comment by aibc-hp** [comment]
非常感谢能立马收到您的回复，很激动！
我也看到了您贴出来的博客，也尝试了那样做，但是没有效果。
我把gcc版本降低到了7.5，RuntimeError: Error building extension  _prroi_pooling问题没了，但是出现了另一个问题subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1. 
此刻我很是苦恼，不知道该往哪个方向去查找错误。
您能否详细的说一下您是怎么解决那个问题的，非常感谢您！

> 我记得是贴了一个博客链接在里面，用那个博客里的方法解决的
> […](#)
> ------------------ Original ------------------ From: aibc-hp ***@***.***&gt; Date: Wed,Apr 6,2022 11:05 PM To: easycodesniper-afk/SiamCSR ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [easycodesniper-afk/SiamCSR] ADRNet (Issue #2) 您好，我想问一个关于ADRNet的问题，我在那里看到了您问作者的问题，RuntimeError: Error building extension _prroi_pooling，您说您已经解决了该问题，我想问一下您是怎么解决的呢？能否详细说说？ 我也遇到了一样的问题，目前在这问题上已经用了两天时间，尝试了很多方法，但还是无法解决。 非常迫切的希望能收到您的回复！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by easycodesniper-afk** [comment]
你的实验环境是什么，包括系统、cuda、gpu等等

**Comment by aibc-hp** [comment]
> 你的实验环境是什么，包括系统、cuda、gpu等等

系统是Linux 20.04
cuda 10.2    有cudnn
gpu只有一块
目前torch版本是 1.7.1  torchvision版本是0.8.2
作者的install.sh也装过，尝试了没有效果

**Comment by aibc-hp** [comment]
> 你的实验环境是什么，包括系统、cuda、gpu等
显卡是RTX 1050Ti

**Comment by easycodesniper-afk** [comment]
> > 你的实验环境是什么，包括系统、cuda、gpu等等
> 
> 系统是Linux 20.04 cuda 10.2 有cudnn gpu只有一块 目前torch版本是 1.7.1 torchvision版本是0.8.2 作者的install.sh也装过，尝试了没有效果

确保你的gcc与g++都安装了对应的版本。

如果仍然有报错，可以尝试切换cuda版本。

**Comment by aibc-hp** [comment]
能否告诉一下您的系统环境，gcc版本，cuda版本，显卡信息等以作参考，非常感谢！

**Comment by easycodesniper-afk** [comment]
> 

我的ubuntu主机目前无法使用，等能够使用的时候帮你看一下。

另外，解决报错的常规做法是使用谷歌搜索，我对你这个报错进行搜索后找到这篇博客，可以尝试一下：

https://blog.csdn.net/zylooooooooong/article/details/113422239

**Comment by aibc-hp** [comment]
> > 
> 
> 我的ubuntu主机目前无法使用，等能够使用的时候帮你看一下。
> 
> 另外，解决报错的常规做法是使用谷歌搜索，我对你这个报错进行搜索后找到这篇博客，可以尝试一下：
> 
> https://blog.csdn.net/zylooooooooong/article/details/113422239
真的有用诶，太感谢您了，现在出现的问题是 CUDA out of memory. 这个是比较常见的问题，就好解决了。
非常感谢您！我也是做多模态跟踪这个方向。
我对您的论文也很感兴趣，忙完这一阶段的工作我就拜读您的论文和代码。
